version: "2"
services:
  inasafe: &inasafe
    build:
      context: ./docker-inasafe
      dockerfile: Dockerfile-dev
    env_file:
      - ./docker-inasafe/realtime-rest-dev.env
    volumes:
      - ./inasafe-src:/home/realtime/src
      - ./analysis_data:/home/realtime/analysis_data
      - ./shakemaps:/home/realtime/shakemaps
      - ./shakemaps-extracted:/home/realtime/shakemaps-extracted
      - ./floodmaps:/home/realtime/floodmaps
      - ./web:/var/www
      - ./pycharm-helpers/inasafe-realtime:/root/.pycharm_helpers
    ports:
      # expose ssh ports
      - "35103:22"

  # exactly the same like inasafe, but with container name to easily identify it
  inasafe-shakemap-monitor:
    build:
      dockerfile: Dockerfile-dev
    command: /start-dev.sh
    volumes:
      - ./pycharm-helpers/inasafe-shakemap-monitor:/root/.pycharm_helpers
    ports:
      - "35104:22"
  #  container_name: shakemap-monitor

  inasafe-shakemap-monitor-bnpb:
    build:
      dockerfile: Dockerfile-dev
    command: /start-dev.sh
    ports:
      - "35105:22"

  inasafe-shakemap-corrected-monitor:
    build:
      dockerfile: Dockerfile-dev
    command: /start-dev.sh
    volumes:
      - ./pycharm-helpers/inasafe-shakemap-corrected-monitor:/root/.pycharm_helpers
    ports:
      - "35106:22"

  inasafe-worker:
    build:
      dockerfile: Dockerfile-dev
